# HNF-Netv2模型配置
model_type: hnfnetv2
in_channels: 1
num_classes: 1
features: [64, 128, 256, 512]

# 训练参数
max_epochs: 100
batch_size: 16
learning_rate: 0.0005
weight_decay: 0.001
min_lr: 0.000001
patience: 12
gradient_clip_val: 1.0

# 数据参数
data_dir: processed_data
img_size: 256
num_workers: 8
fold: 5
center_crop: true

# 输出参数
output_dir: compare_experiments/hnfnetv2_experiment/output
precision: 16 