# BrainTumorSegNet训练配置文件（Proposed Method）
data_dir: /home/wf/data1/cut/brain_tumor_segmentation/processed_data
output_dir: /home/wf/data1/cut/brain_tumor_segmentation/output/braintumsegnet
exp_name: brain_tumor_seg

# 模型配置
model_type: braintumsegnet  # 默认为BrainTumorSegNet，也可写作 proposed_method
in_channels: 1
num_classes: 1
encoder_dims: [64, 128, 256, 512]
decoder_dim: 128
dropout_ratio: 0.1

# 训练参数
batch_size: 16
crop_size: [256, 256]
center_crop: true
num_workers: 4
max_epochs: 100
learning_rate: 3e-4
weight_decay: 0.01
min_lr: 1e-6
patience: 15
gradient_clip_val: 1.0
precision: 32
seed: 42
num_folds: 5

# 类别权重
class_weights: [1.0] 