# SegNet模型配置文件
model_type: 'segnet'
num_classes: 1  # 二分类分割

# 训练参数
batch_size: 16
num_epochs: 100
learning_rate: 0.001
weight_decay: 0.0001
optimizer: 'adam'
scheduler: 'cosine'  # 学习率调度器
warmup_epochs: 5

# 数据处理参数
crop_size: [256, 256]
center_crop: true
num_workers: 4

# 数据增强
augmentation:
  random_flip: true
  random_rotate: true
  random_brightness: true
  random_contrast: true

# 训练设置
num_folds: 5
seed: 42
save_interval: 5  # 每隔多少个epoch保存一次
val_interval: 1   # 每隔多少个epoch验证一次

# 模型特定参数
encoder: 'vgg16'
pretrained: true
batch_norm: true
dropout_rate: 0.5
use_unpooling: true  # 使用最大反池化而不是上采样

# 损失函数配置
loss:
  dice_weight: 1.0
  bce_weight: 1.0

# 评估指标
metrics:
  - 'dice'
  - 'iou'
  - 'precision'
  - 'recall'
  - 'specificity'
  - 'hd95'

# 设备配置
device: 'cuda'
multi_gpu: false 