# 基本配置
exp_name: brain_tumor_seg
output_dir: ./output
seed: 42

# 数据配置
data_dir: ./processed_data
num_folds: 5
in_channels: 1
num_classes: 1
crop_size: [256, 256]
center_crop: true

# 模型配置
model:
  encoder_dims: [64, 128, 256, 512]
  decoder_dim: 128
  dropout_ratio: 0.1

# 训练配置
batch_size: 2
accumulate_grad_batches: 8
learning_rate: 3.0e-4
weight_decay: 0.01
min_lr: 1.0e-6
max_epochs: 100
patience: 10
precision: 32
gradient_clip_val: 1.0

# 数据增强
augmentations:
  use_augmentation: true
  horizontal_flip_prob: 0.5
  vertical_flip_prob: 0.5
  rotation_prob: 0.5
  rotation_degrees: 15
  elastic_deformation_prob: 0.5
  elastic_sigma: 10
  elastic_alpha: 50
  gaussian_noise_prob: 0.5
  contrast_prob: 0.5
  contrast_limit: 0.2
  brightness_prob: 0.5
  brightness_limit: 0.15

# 损失函数配置
loss:
  dice_weight: 0.7
  bce_weight: 0.3
  smooth: 1.0e-5
  class_weights: [0.5, 0.3, 0.2]  # ET, TC, WT 的权重

# 评估配置
evaluation:
  metrics: ['dice', 'iou', 'hd95', 'precision', 'recall', 'f1']
  threshold: 0.5
  visualize: true
  save_outputs: true

# 系统配置
num_workers: 4
pin_memory: true 